# Generated by Django 4.2.1 on 2023-06-29 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=45, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', message='Este campo solo permite letras.')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=45, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', message='Este campo solo permite letras.')]),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='unidades',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', message='Este campo solo permite números.')]),
        ),
    ]
