# Generated by Django 4.2.1 on 2023-06-29 21:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_categoria_nombre_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=45, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(blank=True, max_length=45, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', message='Este campo solo permite letras.')]),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='subcategoria',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='producto.subcategoria'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=45, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='marca',
            field=models.CharField(blank=True, max_length=45, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Categoria', to='producto.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, choices=[('1', 'Azul'), ('2', 'Rojo'), ('3', 'Amarillo'), ('4', 'Verde'), ('5', 'Negro')], max_length=45, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=45, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Marca', to='producto.marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='material',
            field=models.CharField(blank=True, choices=[('1', 'Metal'), ('2', 'Plastico'), ('3', 'Hierro')], max_length=45, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(blank=True, max_length=45, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', message='Este campo solo permite letras.')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.CharField(blank=True, max_length=45, validators=[django.core.validators.RegexValidator('^\\d+$', message='Este campo solo permite números.')], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(blank=True, choices=[('1', 'Bolsa'), ('2', 'Caja')], max_length=45, verbose_name='Presentacion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidades',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Unidades', to='producto.unidades'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=45, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('Construccion', 'Construcción'), ('Electricidad', 'Electricidad'), ('Herramientas Manual', 'Herramientas Manual'), ('Plomeria y Tuberias', 'Plomeria y Tuberias')], max_length=45, verbose_name='Subcategoria'),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=45, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='medida',
            field=models.CharField(blank=True, choices=[('1', 'Pulgada'), ('2', 'Centimetro'), ('3', 'Milimetros'), ('4', 'Kilos'), ('5', 'Miligramos'), ('6', 'Libras')], max_length=45, verbose_name='Medida'),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='unidades',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', message='Este campo solo permite números.')]),
        ),
    ]
