# Generated by Django 4.2.1 on 2023-06-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='fecha_entrega',
            field=models.DateField(auto_now=True, default=1, help_text='MM/DD/AAAA', verbose_name='Fecha entrega'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='fecha_envio',
            field=models.DateField(auto_now=True, default=1, help_text='MM/DD/AAAA', verbose_name='Fecha envio'),
            preserve_default=False,
        ),
    ]
