# Generated by Django 4.2.1 on 2023-06-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_domicilio_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='fecha_entrega',
            field=models.DateField(help_text='MM/DD/AAAA', null=True, verbose_name='Fecha entrega'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='fecha_envio',
            field=models.DateField(help_text='MM/DD/AAAA', null=True, verbose_name='Fecha envio'),
        ),
    ]
