# Generated by Django 4.2.1 on 2023-06-29 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_egreso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='cantidad',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', message='Este campo solo permite números.')]),
        ),
    ]
