# Generated by Django 4.2.1 on 2023-06-29 21:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_domicilio_fecha_entrega_and_more'),
        ('producto', '0003_alter_categoria_estado_alter_categoria_nombre_and_more'),
        ('compras', '0003_cuenta_pendiente_nombre_producto_alter_compra_estado_and_more'),
        ('ingreso_egreso', '0002_alter_detalle_venta_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='compra',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='compras.compra', verbose_name='Compra'),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=45, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='precio_compra',
            field=models.PositiveIntegerField(blank=True, max_length=45, verbose_name='Precio de compra'),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='precio_venta',
            field=models.PositiveIntegerField(blank=True, max_length=45, verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='producto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto', verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='cantidad',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', message='Este campo solo permite números.')]),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=45, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='nombre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto', verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='venta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.venta', verbose_name='Venta'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cantidad',
            field=models.SmallIntegerField(blank=True, max_length=45, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='detalle_compra',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ingreso_egreso.detalle_compra', verbose_name='Detalle compra'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='detalle_venta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ingreso_egreso.detalle_venta', verbose_name='Detalle venta'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=45, verbose_name='Estado'),
        ),
    ]
