# Generated by Django 4.2.1 on 2023-06-29 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='municipio',
            field=models.CharField(max_length=45, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', message='Este campo solo permite letras.')]),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=45, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', message='Este campo solo permite letras.')]),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', message='Este campo solo permite números.')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=45, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', message='Este campo solo permite letras.')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(blank=True, max_length=45, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Por favor, ingresa una dirección de correo electrónico válida.')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=15, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', message='Este campo solo permite números.')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=45, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=45, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', message='Este campo solo permite letras.')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Admin', 'Administrador'), ('Empleado', 'Empleado'), ('Usuario', 'Usuario')], max_length=10, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^\\d+$', message='Este campo solo permite números.')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extrangería')], max_length=2, verbose_name='Tipo de Documento'),
        ),
    ]
