# Generated by Django 4.2.1 on 2023-06-29 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_sucursal_municipio_alter_sucursal_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(blank=True, max_length=45, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=45, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='municipio',
            field=models.CharField(blank=True, max_length=45, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', message='Este campo solo permite letras.')]),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(blank=True, max_length=45, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', message='Este campo solo permite letras.')]),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', message='Este campo solo permite números.')]),
        ),
    ]
